Repository P3tConnect/pawthera, pull requests merged in 2024-09, with the labels that each got.

#223 Navbar responsive / responsive Dashboard and TimeTable Page
  app/[locale]/(main)/dashboard/@pro/page.tsx
  app/[locale]/(main)/dashboard/@pro/timetable/page.tsx
  app/globals.css
  components/dashboard/layout/dashboard-layout.tsx
  components/dashboard/layout/navbar.tsx
  components/dashboard/layout/new-shortcut.tsx
  components/dashboard/layout/sheet-menu.tsx
  components/dashboard/layout/sidebar-toggle.tsx
  components/dashboard/layout/sidebar.tsx
  components/dashboard/shortcuts/timetable-widget.tsx
  components/ui/chart.tsx
  package.json
Labels: Improvement

#229 Refactoring menu map list
  app/[locale]/(main)/dashboard/[companyId]/layout.tsx
  components/dashboard/layout/dashboard-layout.tsx
  components/dashboard/layout/navbar.tsx
  src/config/menu-list.ts
  src/trigger/example.trigger.ts
  src/trigger/index.ts
Labels: enhancement, Logic, Improvement

#231 Merge from Paw-27
  app/[locale]/(auth)/login/page.tsx
  app/[locale]/(main)/companies/[id]/page.tsx
  app/[locale]/(main)/companies/page.tsx
  bun.lockb
  components/company/zone-section.tsx
  components/dashboard/pages/reminders-page/reminders-list.tsx
  components/dashboard/shortcuts/timetable-widget.tsx
  components/landing/footer.tsx
  components/landing/section.tsx
  next-auth.d.ts
  package.json
  src/actions/reminders.action.ts
  src/actions/user.action.ts
  src/config/siteConfig.ts
  src/config/siteConfig.tsx
  src/drizzle/meta/0001_snapshot.json
  src/drizzle/meta/_journal.json
  src/lib/auth.ts
  src/lib/db.ts
  src/lib/schemas.ts
Labels: Feature, Logic, Screen
