Repository P3tConnect/pawthera, pull requests merged in 2024-10, with the labels that each got.

#233 Page Agenda (paw/23)
  app/[locale]/(main)/dashboard/[companyId]/@owner/page.tsx
  app/[locale]/(main)/dashboard/[companyId]/@owner/timetable/page.tsx
  app/globals.css
  bun.lockb
  components/company-details/calendar.css
  components/company-details/rates-section.tsx
  components/company-details/timetable-full-width.tsx
  components/company-details/timetablefullwidth.tsx
  components/dashboard/shortcuts/components/calendar-dropdown.tsx
  drizzle.config.ts
  src/drizzle/0000_fantastic_iron_lad.sql
  src/drizzle/0001_broken_greymalkin.sql
  src/drizzle/0001_friendly_moonstone.sql
  src/drizzle/meta/0000_snapshot.json
  src/drizzle/meta/0001_snapshot.json
  src/drizzle/meta/_journal.json
Labels: Feature, Screen

#236 Feature/paw 234
  app/[locale]/(auth)/sign-in/[[...sign-in]]/page.tsx
  app/[locale]/(main)/dashboard/@client/layout.tsx
  app/[locale]/(main)/dashboard/[companyId]/@owner/timetable/page.tsx
  app/[locale]/(main)/dashboard/[companyId]/layout.tsx
  app/[locale]/(main)/dashboard/layout.tsx
  app/[locale]/layout.tsx
  app/globals.css
  components/company-details/hero.tsx
  components/company-details/rates-section.tsx
  components/company-details/timetable-full-width.tsx
  components/company-details/timetablefullwidth.tsx
  components/company-details/zone-section.tsx
  components/dashboard/layout/collapse-menu-button.tsx
  components/dashboard/layout/dashboard-bubbles.tsx
  components/dashboard/layout/dashboard-layout.tsx
  components/dashboard/layout/menu.tsx
  components/dashboard/layout/navbar.tsx
  components/dashboard/layout/new-shortcut.tsx
  components/dashboard/layout/user-nav.tsx
  components/dashboard/shortcuts/clients-widget.tsx
  components/dashboard/shortcuts/components/calendar-dropdown.tsx
  components/dashboard/shortcuts/expenses-widget.tsx
  components/dashboard/shortcuts/sales-widget.tsx
  components/dashboard/shortcuts/timetable-widget.tsx
  components/feature_scroll.tsx
  components/features-horizontal.tsx
  components/landing/cta-section.tsx
  components/landing/drawer.tsx
  components/landing/faq.tsx
  components/landing/features.tsx
  components/landing/header.tsx
  components/landing/hero.tsx
  components/landing/menu.tsx
  components/landing/pricings.tsx
  components/landing/problem.tsx
  components/landing/section.tsx
  components/landing/solution.tsx
  components/macbook-scroll.tsx
  components/magicui/bento-grid.tsx
  components/safari.tsx
  components/ui/badge.tsx
  components/ui/bento-grid.tsx
  components/ui/button.tsx
  global.d.ts
  middleware.ts
  next.config.mjs
  package.json
  public/messages/en.json
  public/messages/fr.json
  src/i18n/index.ts
  src/i18n/request.ts
  src/i18n/routing.ts
  src/lib/current-user.ts
  src/locales/client.ts
  src/locales/en.ts
  src/locales/fr.ts
  src/locales/index.ts
  src/locales/server.ts
Labels: Feature, Screen, Improvement

#240 Implement client dashboard pages and layout changes
  app/[locale]/(main)/dashboard/@client/layout.tsx
  app/[locale]/(main)/dashboard/@client/page.tsx
  app/[locale]/(main)/dashboard/@client/pets/page.tsx
  app/[locale]/(main)/dashboard/@client/timetable/page.tsx
  app/[locale]/(main)/dashboard/[companyId]/layout.tsx
  app/[locale]/(main)/dashboard/layout.tsx
  components/dashboard/shortcuts/reminders-shortcut.tsx
  src/db/company.ts
Labels: Feature, Component

#242 wip progression widget
  app/[locale]/(main)/dashboard/[companyId]/layout.tsx
  app/[locale]/(marketing)/waitlist/page.tsx
  app/[locale]/layout.tsx
  app/globals.css
  components/dashboard/layout/dashboard-layout.tsx
  components/dashboard/layout/mode-toggle.tsx
  components/dashboard/layout/navbar.tsx
  components/dashboard/layout/notifications.tsx
  components/dashboard/layout/search-button.tsx
  components/dashboard/layout/sidebar-toggle.tsx
  components/dashboard/layout/sidebar.tsx
  components/dashboard/shortcuts/clients-widget.tsx
  components/dashboard/shortcuts/expenses-widget.tsx
  components/dashboard/shortcuts/incoming-reservations-widget.tsx
  components/dashboard/shortcuts/progression-widget.tsx
  components/dashboard/shortcuts/reminders-shortcut.tsx
  components/dashboard/shortcuts/reservations-statuses-widget.tsx
  components/dashboard/shortcuts/sales-widget.tsx
  components/dashboard/shortcuts/timetable-widget.tsx
  components/index.ts
  components/landing/faq.tsx
  components/landing/hero.tsx
  components/landing/problem.tsx
  components/landing/solution.tsx
  components/magicui/bento-grid.tsx
  components/magicui/blur-fade.tsx
  components/magicui/feature_scroll.tsx
  components/magicui/features-horizontal.tsx
  components/magicui/macbook-scroll.tsx
  components/magicui/safari.tsx
  components/nav-user.tsx
  components/site-footer.tsx
  components/ui/button.tsx
  components/ui/card.tsx
  components/ui/input.tsx
  components/ui/separator.tsx
  components/ui/sheet.tsx
  components/ui/sidebar.tsx
  components/ui/skeleton.tsx
  components/ui/tooltip.tsx
  hooks/use-mobile.tsx
  middleware.ts
  package.json
  public/messages/en.json
  public/messages/fr.json
  src/context/providers.tsx
  src/hooks/use-mobile.tsx
  tailwind.config.js
  tsconfig.json
Labels: enhancement, Screen, Component
